# Generated by Django 5.2.1 on 2025-05-31 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=200, verbose_name="Улица")),
                (
                    "house_number",
                    models.CharField(max_length=20, verbose_name="Номер дома"),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Квартира"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Почтовый индекс"),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
                "ordering": ["city", "street"],
            },
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "sneakers_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID кроссовок"
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Бренд")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sneakers/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Товар в каталоге",
                "verbose_name_plural": "Каталог товаров",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("kids", "Детская"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "client_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID клиента"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата регистрации",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "position_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID должности"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название должности"
                    ),
                ),
                ("responsibilities", models.TextField(verbose_name="Обязанности")),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальная зарплата",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальная зарплата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID заказа"
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата заказа"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Общая сумма"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Номер отслеживания",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "В обработке"),
                            ("shipped", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_orders",
                        to="sneaker_app.clients",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="sneaker_app.address",
                        verbose_name="Адрес доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("size", models.CharField(max_length=100, verbose_name="Размеры")),
                ("color", models.CharField(max_length=100, verbose_name="Цвет")),
                ("material", models.CharField(max_length=100, verbose_name="Материал")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_cards",
                        to="sneaker_app.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "sneakers",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_card",
                        to="sneaker_app.catalog",
                        verbose_name="Кроссовки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка товара",
                "verbose_name_plural": "Карточки товаров",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "purchase_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID покупки"
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата покупки"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Общая стоимость"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_purchases",
                        to="sneaker_app.clients",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "sneakers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="sneaker_app.catalog",
                        verbose_name="Кроссовки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка",
                "verbose_name_plural": "Покупки",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "employee_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID сотрудника"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        max_length=255, verbose_name="Контактная информация"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата найма"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="sneaker_app.positions",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник поддержки",
                "verbose_name_plural": "Сотрудники поддержки",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "review_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID отзыва"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 звезда"),
                            (2, "2 звезды"),
                            (3, "3 звезды"),
                            (4, "4 звезды"),
                            (5, "5 звезд"),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Одобрен"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_reviews",
                        to="sneaker_app.clients",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "sneakers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="sneaker_app.catalog",
                        verbose_name="Кроссовки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_date"],
                "unique_together": {("client", "sneakers")},
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "wishlist_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID записи"
                    ),
                ),
                ("size", models.CharField(max_length=100, verbose_name="Размер")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_wishlist",
                        to="sneaker_app.clients",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "sneakers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_wishlist",
                        to="sneaker_app.catalog",
                        verbose_name="Кроссовки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список желаний",
                "verbose_name_plural": "Списки желаний",
                "ordering": ["-added_date"],
                "unique_together": {("client", "sneakers", "size")},
            },
        ),
    ]
