# Generated by Django 5.2.1 on 2025-06-01 19:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sneaker_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название тега"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Цвет в формате HEX (#ffffff)",
                        max_length=7,
                        verbose_name="Цвет тега",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="productcards",
            name="manufacturer_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на страницу товара у производителя",
                null=True,
                verbose_name="Ссылка на сайт производителя",
            ),
        ),
        migrations.AddField(
            model_name="productcards",
            name="official_store_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на товар в официальном интернет-магазине",
                null=True,
                verbose_name="Ссылка на официальный магазин",
            ),
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Приоритет отображения тега (0-100)",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sneaker_app.catalog",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sneaker_app.tag",
                        verbose_name="Тег",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег товара",
                "verbose_name_plural": "Теги товаров",
                "ordering": ["-priority", "added_at"],
                "unique_together": {("product", "tag")},
            },
        ),
        migrations.AddField(
            model_name="catalog",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="sneaker_app.ProductTag",
                to="sneaker_app.tag",
                verbose_name="Теги",
            ),
        ),
    ]
